### ISSUE TITLE
Snowflake使用Autofac会出现时间倒退问题

### ISSUE THREAD

**Issue by LingDian2019** [NewLifeX/X#107]
问题现象
在使用过程发现雪花算法会出现时间倒退问题，如何不用Autofac就不会出现这个问题，测试过程只是在源码Test上加入了Autofac

测试截图
![image](https://user-images.githubusercontent.com/49890738/170906772-661a01bf-9061-49d5-a248-974f373e6769.png)
![image](https://user-images.githubusercontent.com/49890738/170906798-3c351044-5481-4472-9a8b-accfe8ef4655.png)
![}5MAJI@%R~DFA0SUIO93BVI](https://user-images.githubusercontent.com/49890738/170906806-4dc24ea4-1e03-4136-9aa4-35bd97090537.jpg)

**Comment by nnhy** [comment]
这个时间差1ms是怎么测算的？

**Comment by nnhy** [comment]
原因是：
多线程生成Id的时候，_lastTime在计算差值前被另一个线程更新了，导致时间有微小偏差（一般是1ms）。
代码设计会自动修正时间，由于seq是原子操作，所以并不影响雪花Id的唯一性。
 
注释掉日志代码就好，不影响使用
