### ISSUE TITLE
Socket.OSSupportsIPv6 不支持Xamarin.Android 

### ISSUE THREAD

**Issue by top5five** [NewLifeX/X#115]
在Xamarin.Android,中不支持Socket.OSSupportsIPv6 判断，在判断IPV6始终返回ture,导致端口重复打开.

[https://github.com/NewLifeX/X/blob/master/NewLife.Core/Net/NetServer.cs](url)

 ISocketServer[] CreateServer<TServer>(IPAddress address, Int32 port, AddressFamily family) where TServer : ISocketServer, new()
    {
        var list = new List<ISocketServer>();
        switch (family)
        {
            case AddressFamily.InterNetwork:
            case AddressFamily.InterNetworkV6:
                var addr = address.GetRightAny(family);
                if (addr != null)
                {
                    var svr = new TServer();
                    svr.Local.Address = addr;
                    svr.Local.Port = port;
                    //svr.AddressFamily = family;
                    svr.Tracer = Tracer;

                    // 协议端口不能是已经被占用
                    if (!svr.Local.CheckPort()) list.Add(svr);
                }
                break;
            default:
                // 其它情况表示同时支持IPv4和IPv6
                // 兼容Linux
                //if (Socket.OSSupportsIPv4)
                list.AddRange(CreateServer<TServer>(address, port, AddressFamily.InterNetwork));
               //修改判断 如果是Mono就默认不支持IPV6
                if (Socket.OSSupportsIPv6 && !Runtime.Mono ) list.AddRange(CreateServer<TServer>(address, port, AddressFamily.InterNetworkV6));
                break;
        }

        return list.ToArray();
    }

微软对于Socket.OSSupportsIPv4 和 Socket.OSSupportsIPv6 支持说明
[https://learn.microsoft.com/zh-cn/dotnet/api/system.net.sockets.socket.ossupportsipv4?view=net-7.0](url)
[https://learn.microsoft.com/zh-cn/dotnet/api/system.net.sockets.socket.ossupportsipv6?view=net-7.0](url)

**Comment by nnhy** [comment]
没有看明白修改了哪里

**Comment by nnhy** [comment]
终于看到了那个 Runtime.Mono
