### ISSUE TITLE
NewLife.Hive套接字连接出错

### ISSUE THREAD

**Issue by damonxx** [NewLifeX/X#118]
.NET 4.5.1版本上NewLife.Hive使用报错：
System.Net.Sockets.SocketException:“由于套接字没有连接并且(当使用一个 sendto 调用发送数据报套接字时)没有提供地址，发送或接收数据的请求没有被接受。”

**Comment by nnhy** [comment]
在应用服务器试试telnet到Hive服务器

**Comment by damonxx** [comment]
> 在应用服务器试试telnet到Hive服务器
换其它框架用thrift协议连接是正常的

**Comment by nnhy** [comment]
最近几年Hive用得少，缺乏测试
