### ISSUE TITLE
801升级到1201后报 Not Found InterNetworkV6

### ISSUE THREAD

**Issue by BackT0TheFuture** [NewLifeX/X#131]
相关代码如下

```
            var netUri = new NetUri("tcp://0.0.0.0:19000");
            apiServer = new ApiServer(netUri)
                               {
                                   Tracer = Setting.ApmTracer,
                                   EncoderLog = Setting.Log,
                                   ShowError = true,
                                   ServiceProvider = ioc.BuildServiceProvider()
                               };
            apiServer.Start(); 
```

报错信息如下

![异常](https://github.com/NewLifeX/X/assets/10088733/0e84d84d-3faa-419b-8b67-a380167a6c77)

**Comment by nnhy** [comment]
`
            var netUri = new NetUri("tcp://0.0.0.0:19000");
            var apiServer = new ApiServer(netUri)
            //var apiServer = new ApiServer(19000)
            {
                Log = XTrace.Log,
                ShowError = true,
                //ServiceProvider = ioc.BuildServiceProvider()
            };
            apiServer.Start();
`

以上测试代码重现了这个bug
