### ISSUE TITLE
Config以及Log文件夹能否不自动生成，有配置入口吗

### ISSUE THREAD

**Issue by kimdiego2098** [NewLifeX/X#133]
我只用了其中的缓存功能，这个配置和日志能关掉吗

**Comment by nnhy** [comment]
你可以把代码抠出来，做一个自己的组件。

**Comment by nnhy** [comment]
如果只是用到MemoryCache，把它抠出去好了，它的引用不多，其中有Log和Config命名空间的代码都注释不要
