### ISSUE TITLE
HttpServer怎么实现Server-Sent Event(SSE)功能

### ISSUE THREAD

**Issue by damonxx** [NewLifeX/X#136]
HttpServer怎么实现Server-Sent Event(SSE)功能
context.Response.SetResult()方法不能传递异步stream

**Comment by nnhy** [comment]
这里的HttpServer是轻量级服务器，没有支持太多功能。
你的需要，可以自己扩展实现。

**Comment by nnhy** [comment]
IHttpContext.Connection 是 INetSession 类型对象，表示Tcp连接会话，可以调用它的Send方法，向浏览器发送任意内容。
