### ISSUE TITLE
Redis Add expire 未使用

### ISSUE THREAD

**Issue by flyliao** [NewLifeX/X#14]

**Comment by nnhy** [comment]
dev分支已修正！
`public override Boolean Add<T>(String key, T value, Int32 expire = -1)
{
    if (expire < 0) expire = Expire;

    if (expire <= 0)
        return Execute(rds => rds.Execute<Int32>("SETNX", key, value) == 1, true);
    else
        return Execute(rds => rds.Execute<Int32>("SETNX", key, value, expire) == 1, true);
}
`
