### ISSUE TITLE
请问一下 XCode 支持存储过程查询吗？

### ISSUE THREAD

**Issue by zhang-junlin** [NewLifeX/X#147]
如题，我有一个业务相对来说比较复杂，所以写了个存储过程，但是我没找到 XCode DAL 有对应的方法可以执行这个存储过程。请问一下 XCode 支持存储过程查询吗？

**Comment by nnhy** [comment]
var dal=DAL.Create("Membership");
var dt=dal.Query<User>("select * from user where name=@name", new{name="Stone"});

DAL层支持执行sql和存储过程。
