### ISSUE TITLE
更新11后cpu 暴增 持续走高。恢复10后问题解决

### ISSUE THREAD

**Issue by nodyang** [NewLifeX/X#149]
目前还无法判断问题。但回滚后目前已经恢复正常

**Comment by nnhy** [comment]
抓个dump，用dotTrace分析一下应用在忙什么。
是否引用了其它组件？
例如 Remoting / Stardust / Redis / MQTT /RocketMQ
这些都跟v11有关

**Comment by nodyang** [comment]
没有其他组件 就是v11  等我有时间去恢复下抓一下

**Comment by nodyang** [comment]
目前恢复到v11 短时间并未出现症状。

**Comment by nodyang** [comment]
应该不是newlife.Core 引起的
