### ISSUE TITLE
关于Xcode内置Membership相关表扩展字段（EX1...EX5）

### ISSUE THREAD

**Issue by SweetPT** [NewLifeX/X#18]
最近准备使用魔方框架平台用于项目开发，但是有一个场景是在Membership表（Role）加字段，但是基于Xcode的实体生成类是内置的，没办法修改，先期想了两种方式：

第一：基于Membership内置表加上扩展表进行实现。
优势：不用动Xcode组件；
劣势：对Membership表操作时另外重载基类进行额外操作；

第二：直接用Xcode源码编译重新生成，然后通过添加引用方式进行应用；
优势：不需要额外操作，直接使用；
劣势：后期升级Xcode，需要获取代码把扩展字段重新加上去再编译再引用方式；

最后，才想到如上把Membership内置表加上几个扩展字段的问题，方便使用框架的人直接继承。

另外：用SQLSERVER数据配置文件生成实体时，会有一些连接不上的问题；（配置文件的连接字符串是可以连接到数据的，但是初始化数据时就找不到）

1、00:15:12.745 20 Y 5 Open错误：[无法打开登录所请求的数据库 "MembershipAA"。登录失败。
用户 'AF887JOJ0L3O2W3\Administrator' 登录失败。]Server=.;Integrated Security=SSPI;Database=MembershipAA;Pooling=false;Application Name=XCode_CubeDemo_Membership
00:15:12.746 20 Y 5 [3]GetSchema(MetaDataCollections)异常重试！无法打开登录所请求的数据库 "MembershipAA"。登录失败。
用户 'AF887JOJ0L3O2W3\Administrator' 登录失败。,连接字符串 Server=.;Integrated Security=SSPI;Database=MembershipAA;Pooling=false;Application Name=XCode_CubeDemo_Membership

2、SET NOCOUNT ON;Insert Into [User](Name, Password, DisplayName, Sex, RoleID, RoleIDs, [Online], Enable, Logins, LastLogin, RegisterTime) Values(N'admin', N'21232F297A57A5A743894A0E4A801FC3', N'管理员', 0, 1, N'', 0, 1, 0, {ts'0001-01-01 00:00:00'}, {ts'0001-01-01 00:00:00'});Select SCOPE_IDENTITY()
00:09:44.908 52 Y 21 初始化数据出错！XCode.Exceptions.XSqlException: 从字符串转换日期和/或时间时，转换失败。
从字符串转换日期和/或时间时，转换失败。[SQL:SET NOCOUNT ON;Insert Into [User](Name, Password, DisplayName, Sex, RoleID, RoleIDs, [Online], Enable, Logins, LastLogin, RegisterTime) Values(N'admin', N'21232F297A57A5A743894A0E4A801FC3', N'管理员', 0, 1, N'', 0, 1, 0, {ts'0001-01-01 00:00:00'}, {ts'0001-01-01 00:00:00'});Select SCOPE_IDENTITY()][DB:Membership/SqlServer] ---> System.Data.SqlClient.SqlException: 从字符串转换日期和/或时间时，转换失败。

**Comment by nnhy** [comment]
关于加扩展字段这一点，我比较赞同，有时候新项目的确需要多存一点东西，但是又懒得加新表。
看看其他人的意思，只要有超过5人支持，可以给这些基础表加字段。

另外，大家觉得有没有必要增加部门表和字典表？

**Comment by redheart47** [comment]
这个是可以有的

**Comment by Xusp** [comment]
1、在实际项目中确实需要对User或Role表增加字段的情况，例如想将用户直接绑定到微信或钉钉账户，现在一般是采用增加扩展表的方式来实现，灵活也不用动XCode库，方便今后升级框架。
2、部门表和字典表使用的地方倒是很多，几乎每个系统都会有这样的需求，但是要设计一个能够满足大多数应用场景的部门实体表也挺难的，这就像User表一样，建议可以参考一下吉日嘎啦的设计。
请问字典表是一个通用的结构，可以用到所有的实体上去吗？

**Comment by Xusp** [comment]
针对字典表，我自己的思路是建立一个树形结构，第一层表示该字典应用在哪个实体对象及字段上，下面则表示具体的字典项。再扩展一下Map自定义特性来将字典绑定到具体的对象上，这样就不用创建很多很小的代码表了。

**Comment by gzhcyk** [comment]
1、支持增加部门表
2、字典表增加的意义好像不太大

**Comment by SweetPT** [comment]
魔方平台用SQLSERVER初始化实体数据时登录失败的问题，发现是SQL2008R2就会有问题，SQL2012就没有问题。

**Comment by SweetPT** [comment]
魔方框架平台定位于基础框架平台，我认为应该有必要加组织结构以及数据字典表，因为对应用户管理基本上肯定有所属部门，这种场景非常多。如果用不上在使用魔方平台的时候完全可以隐藏字段就可以了。另外数据字典也是非常有必要，不然的话完全自己建表或者配置文件存储数据。

1、组织机构（部门表）上下级结构，字段值至少包括是否有效。对应原有的用户表（User）应该加一个组织机构ID。
2、数据字典包括数据【字典类别，数据字典项】（1-N），字段值至少包括是否有效。

**Comment by snakorse** [comment]
搞个json字段行不行

**Comment by nnhy** [comment]
`  <Table Name="Department" Description="部门。组织机构，多级树状结构" BaseType="EntityTree" RenderGenEntity="true">
    <Columns>
      <Column Name="ID" DataType="Int32" Identity="True" PrimaryKey="True" Description="编号" />
      <Column Name="Code" DataType="String" Description="代码" />
      <Column Name="Name" DataType="String" Master="True" Nullable="False" Description="名称" />
      <Column Name="FullName" DataType="String" Length="200" Description="全名" />
      <Column Name="ParentID" DataType="Int32" Description="父级" />
      <Column Name="Level" DataType="Int32" Description="层级。树状结构的层级" />
      <Column Name="Sort" DataType="Int32" Description="排序。同级内排序" />
      <Column Name="Enable" DataType="Boolean" Description="启用" />
      <Column Name="Visible" DataType="Boolean" Description="可见" />
      <Column Name="Ex1" DataType="Int32" Description="扩展1" />
      <Column Name="Ex2" DataType="Int32" Description="扩展2" />
      <Column Name="Ex3" DataType="Double" Description="扩展3" />
      <Column Name="Ex4" DataType="String" Description="扩展4" />
      <Column Name="Ex5" DataType="String" Description="扩展5" />
      <Column Name="Ex6" DataType="String" Description="扩展6" />
      <Column Name="CreateUser" DataType="String" Description="创建用户" />
      <Column Name="CreateUserID" DataType="Int32" Description="创建用户" />
      <Column Name="CreateIP" DataType="String" Description="创建地址" />
      <Column Name="CreateTime" DataType="DateTime" Description="创建时间" />
      <Column Name="UpdateUser" DataType="String" Description="更新用户" />
      <Column Name="UpdateUserID" DataType="Int32" Description="更新用户" />
      <Column Name="UpdateIP" DataType="String" Description="更新地址" />
      <Column Name="UpdateTime" DataType="DateTime" Description="更新时间" />
      <Column Name="Remark" DataType="String" Length="200" Description="备注" />
    </Columns>
    <Indexes>
      <Index Columns="Name" />
      <Index Columns="ParentID,Name" Unique="True" />
      <Index Columns="Code" />
      <Index Columns="UpdateTime" />
    </Indexes>
  </Table>
`

**Comment by nnhy** [comment]
```xml
  <Table Name="Parameter" Description="字典参数" ConnName="Log">
    <Columns>
      <Column Name="ID" DataType="Int32" Identity="True" PrimaryKey="True" Description="编号" />
      <Column Name="Category" DataType="String" Description="类别" />
      <Column Name="Name" DataType="String" Master="True" Description="名称" />
      <Column Name="Value" DataType="String" Length="200" Description="数值" />
      <Column Name="LongValue" DataType="String" Length="2000" Description="长数值" />
      <Column Name="Kind" DataType="Int32" Description="种类。0普通，21列表，22名值" Type="XCode.Membership.ParameterKinds" />
      <Column Name="Enable" DataType="Boolean" Description="启用" />
      <Column Name="Ex1" DataType="Int32" Description="扩展1" />
      <Column Name="Ex2" DataType="Int32" Description="扩展2" />
      <Column Name="Ex3" DataType="Double" Description="扩展3" />
      <Column Name="Ex4" DataType="String" Description="扩展4" />
      <Column Name="Ex5" DataType="String" Description="扩展5" />
      <Column Name="Ex6" DataType="String" Description="扩展6" />
      <Column Name="CreateUser" DataType="String" Description="创建用户" />
      <Column Name="CreateUserID" DataType="Int32" Description="创建用户" />
      <Column Name="CreateIP" DataType="String" Description="创建地址" />
      <Column Name="CreateTime" DataType="DateTime" Description="创建时间" />
      <Column Name="UpdateUser" DataType="String" Description="更新用户" />
      <Column Name="UpdateUserID" DataType="Int32" Description="更新用户" />
      <Column Name="UpdateIP" DataType="String" Description="更新地址" />
      <Column Name="UpdateTime" DataType="DateTime" Description="更新时间" />
      <Column Name="Remark" DataType="String" Length="200" Description="备注" />
    </Columns>
    <Indexes>
      <Index Columns="Category,Name" Unique="True" />
      <Index Columns="Name" />
      <Index Columns="UpdateTime" />
    </Indexes>
  </Table>
```

**Comment by nnhy** [comment]
```csharp
var p = Parameter.FindByCategoryAndName("量化交易", "交易所");
if (p == null) p = new Parameter
{
    Category = "量化交易",
    Name = "交易所"
};
var dic = new Dictionary<Int32, String>
{
    [1] = "上海交易所",
    [2] = "深圳交易所",
    [900] = "纽约交易所"
};
p.SetValue(dic);
p.Save();

var p2 = Parameter.FindByCategoryAndName("量化交易", "交易所");
var dic2 = p2.GetHash<Int32, String>();
foreach (var item in dic2)
{
    Console.WriteLine("{0}={1}", item.Key, item.Value);
}
Console.WriteLine(p2.ToJson(true));
p2.Delete();
```
