### ISSUE TITLE
批量删除支持

### ISSUE THREAD

**Issue by nnhy** [NewLifeX/X#20]
目标：
list.Delete(true) 功能增强，不再遍历逐行删除，而是生成 delete from table where id in(1,2,3,4,5) 或者 where id>=1 and id<=5 的语句，批量处理，提升性能。

扩展点：
EntityExtension.cs，扩展 BatchDelete 方法
调整 list.Delete(true)，有条件调用 BatchDelete

注意点：
针对自增主键，生成 id>=1 and id<=5 可能效果更好

欢迎补充意见！~

**Comment by jeerisguo** [comment]
in 靠谱点，大于小于不连续

**Comment by nnhy** [comment]
可以判断连续性，然后混合使用。
 比如： where id>=1 and id<=3 or id in(5,7,9)

**Comment by nnhy** [comment]
已支持批量删除，采用in方法，将来再评估是否采用区间判断。

https://github.com/NewLifeX/X/commit/d1153211da9dd6160108e9efb604c7fd742bb354
