### ISSUE TITLE
dotnetcore 项目 appsettings.json设置数据库链接不起作用

### ISSUE THREAD

**Issue by xxred** [NewLifeX/X#21]
- 默认读取输出目录的 项目名.exe.config或者app.config，appsettings.json设置输出到目录。
- 右键此文件-属性-复制到输出目录选择如果较新则复制
- 并且不支持多开发环境配置文件

**Comment by stwflyfox** [comment]
获取最新代码已可以读取 appsettings.json 里的连结字符串， asp.net core 2.1 的项目，执行过程中报找不到文件：
System.Configuration.ConfigurationManager，，
![image](https://user-images.githubusercontent.com/3983204/58847964-508bff00-86b7-11e9-8cc5-0e19ba69a1da.png)

**Comment by xxred** [comment]
@stwflyfox  https://github.com/NewLifeX/X/issues/30
