### ISSUE TITLE
所有依赖NewLife.Core或者XCode的其他组件源码库提示找不到Nuget包

### ISSUE THREAD

**Issue by xxred** [NewLifeX/X#24]
- 由于新生命团队的组件越来越多的，在完善的过程中需要同时完善基础库，但是NewLife.Core或者XCode不会频繁发布到Nuget，因此采取本地Nuget包源的方法。
- 这不仅解决了上述所说的问题，还方便调试到基础库，因为本地包源的库是需要自己生成的，详见[设置 Nuget 本地源、在线私有源、自动构建打包](https://www.cnblogs.com/xxred/p/10604924.html)
- 因此，此问题需要自己拉取基础库源码生成Nuget包，或者将依赖包自行改成Nuget.org中发布的版本。但不建议这样做，因为可能Nuget.org中的版本并不是最新修改，可能与源码的一些修改对不上

**Comment by nnhy** [comment]
目前每个月月初发布新版正式版，每一两周发布一次beta版或者rc版
