### ISSUE TITLE
XCode动态表名

### ISSUE THREAD

**Issue by j4587698** [NewLifeX/X#26]
XCode是否有办法动态绑定表名？有类似需要修改表前缀的需求。简单看了一下XCode没有发现动态绑定的办法，BindTable与Xml貌似都只能在开发阶段写死表名。

**Comment by nnhy** [comment]
BindTable绑定的表名，称之为默认表名。
实体类所用表名，来自于静态内嵌类Meta.TableName，它是线程静态成员，取默认表名，也可以由用户代码动态修改为任意表名，且只影响当前线程。
例如： Meta.TableName = "user" + k;

这是分表分库的核心点！
分库：Meta.ConnName = "db" + m;

**Comment by Xusp** [comment]
使用分库分表时不能使用异步保存SaveAsync()；

**Comment by nnhy** [comment]
分表分库是不能直接使用SaveAsync，而需要自己用延迟队列，精细化控制

**Comment by nnhy** [comment]
分表分库（百亿级大数据存储） · 语雀
https://www.yuque.com/smartstone/xcode/division

实体队列（多线程生产的大数据集中保存） · 语雀
https://www.yuque.com/smartstone/xcode/queue
