### ISSUE TITLE
需要获取redis缓存所有的所有键,报错“字符串的长度只能为一个字符。”

### ISSUE THREAD

**Issue by vfeihuang** [NewLifeX/X#27]
需要获取redis缓存所有的所有keys,报错“字符串的长度只能为一个字符。”

初始：
`public NewLifeRedis(int dbIndex = 0) {
            if (Core == null) { 
                FullRedis.Register(); 
                Core = Redis.Create(redisConfig.ServerConStr, dbIndex); 
            }
        }`

方法：
`      /// <summary>
        /// 获取所有的键，并根据指定的开头搜索
        /// </summary>
        /// <param name="parttern"></param>
        /// <returns></returns>
        public List<string> GetAllKeys(string parttern = null) {
            var allKeys = Core.Keys;
            if (allKeys != null && allKeys.Count > 0) {
                if (parttern == null)
                    return allKeys.ToList();
                else
                    return allKeys.Where(x => x.StartsWith(parttern)).ToList();
            }
            else
                return null;
        }`

报错：
 字符串的长度只能为一个字符。
说明: 执行当前 Web 请求期间，出现未经处理的异常。请检查堆栈跟踪信息，以了解有关该错误以及代码中导致错误的出处的详细信息。 

异常详细信息: System.FormatException: 字符串的长度只能为一个字符。
源错误: 
[没有相关的源行]
源文件: d:\Project\2013\smls2015New\Cacher\NewLifeRedis.cs    行: 0 
堆栈跟踪: 
[FormatException: 字符串的长度只能为一个字符。]
   System.Convert.ToChar(String value, IFormatProvider provider) +12718388
   System.String.System.IConvertible.ToChar(IFormatProvider provider) +9
   System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider) +12938146
   System.Convert.ChangeType(Object value, Type conversionType) +32
   NewLife.Reflection.DefaultReflect.ChangeType(Object value, Type conversionType) +770
   NewLife.Caching.RedisClient.FromBytes(Packet pk, Type type) +201
   NewLife.Caching.RedisClient.TryChangeType(Object value, Type type, Object& target) +425
   NewLife.Caching.RedisClient.Execute(String cmd, Object[] args) +183
   NewLife.Caching.Redis.get_Keys() +129
   Cacher.NewLifeRedis.GetAllKeys(String parttern) in d:\Project\2013\XXXX\Cacher\NewLifeRedis.cs:0

 
版本号：
NewLife.Core version=8.1.2019.510
NewLife.Redis version=2.1.6951.393

请时间请帮忙看下，谢谢

**Comment by nnhy** [comment]
已确认这是一个bug，通过nuget更新NewLife.Core即可

**Comment by nnhy** [comment]
貌似你用的已经是最新版0510，按说已经通过了单元测试

**Comment by nnhy** [comment]
该BUG源自于Redis.Keys错误把响应类型String[]写为了String所致，0430已修正！

Redis基础测试和集合测试通过 · NewLifeX/X@facfd99
https://github.com/NewLifeX/X/commit/facfd99719c88d5b0dc3d713cf486b61c9025668
