### ISSUE TITLE
BatchUpdate报错

### ISSUE THREAD

**Issue by zilo555** [NewLifeX/X#29]
将FindAll查询出的结果 更改了某个字段后
然后将结果.BatchUpdate()然后报错
System.NotSupportedException:“不支持所指定的方法。”

**Comment by nnhy** [comment]
目前只有Oracle支持BatchUpdate，MySql和SQLite可以尝试 Upsert/BatchUpsert
批处理都是利用了数据库某些特性，所以通用性收到一定限制。

你也可以尝试 list.Update(true)，内部将自动选择批量保存（如果支持）或者事务保存（不支持批量）
