### ISSUE TITLE
dotnetcore 项目中使用MySql驱动报找不到某个程序集的错

### ISSUE THREAD

**Issue by xxred** [NewLifeX/X#30]
凡是报找不到某个程序集，都是由于没有安装Mysql驱动对应的依赖，解决方法有两种：
1. Nuget安装`MySql.Data`，这样相关的依赖就会自动安装
2. 报错说缺什么就装什么，全部手动装上，大概四五个这样子
![image](https://user-images.githubusercontent.com/19650464/58848420-1b80ac00-86b9-11e9-8cb8-0d66720686ff.png)

**Comment by stwflyfox** [comment]
nuget安装Mysql驱动后，此问题已解决，

**Comment by nnhy** [comment]
X组件驱动库已更新，支持netcore版MySql驱动。
https://x.newlifex.com
