### ISSUE TITLE
 XTrace.UseWinForm();

### ISSUE THREAD

**Issue by MarshalT** [NewLifeX/X#31]
用XTrace.UseWinForm();直接就抛异常了。
![image](https://user-images.githubusercontent.com/33778588/60580966-96241080-9db8-11e9-9e11-d6b83d2a881e.png)

**Comment by nnhy** [comment]
这一句，必须卸载入口main函数中，一般写在第一行。
它会拦截全局异常并输出日志

**Comment by MarshalT** [comment]
这个是个坑啊。我放Main函数了，虽然不报错但是异常异常没有拦截到哦。
![image](https://user-images.githubusercontent.com/33778588/60778080-14d9ce80-a168-11e9-8511-16bace3e6e69.png)

**Comment by nnhy** [comment]
不要vs调试，双击exe跑起来

**Comment by MarshalT** [comment]
可以了，多谢
