### ISSUE TITLE
你好，xcode输出的sql日志，会从中间截断，请问怎么输出完整的

### ISSUE THREAD

**Issue by christan-duplicate** [NewLifeX/X#32]
你好，xcode输出的sql日志，会从中间截断，请问怎么输出完整的sql语句？

**Comment by nnhy** [comment]
xcode.config 里面有个配置 SQLMaxLength ，默认长度4096，超长则中间显示点号

**Comment by christan-duplicate** [comment]
好的，多谢，这个属性应该是后面加的，以前没有

**Comment by nnhy** [comment]
是的，之前有人遇到了这样的问题，我们也要类似需求，后来在群友建议下，加了个配置，并且默认长度从1024改为4096
