### ISSUE TITLE
拼音转换工具

### ISSUE THREAD

**Issue by MarshalT** [NewLifeX/X#37]
发现一个BUG 拼音的工具。不认识“焓” 字
![image](https://user-images.githubusercontent.com/33778588/64102308-43f47100-cda2-11e9-8e2b-cd5ffdd16190.png)

**Comment by nnhy** [comment]
翻一下代码，看看是不是基本汉字里面没这个字。
这个时候，可以用微软那个扩展库，里面有所有汉字。
NewLife.Core 是内置了所有区位码的拼音
