### ISSUE TITLE
反向工程，不能自动建立数据库，有数据库时，建立数据表没问题

### ISSUE THREAD

**Issue by armku** [NewLifeX/X#45]
VS2019 X64系统，用nuget上的NewLife.XCode,版本号9.14.2019.1212。没有库时，不能自动建立库，有库时（空白库，只有库名也可），使用正常。

**Comment by nnhy** [comment]
XCode反向工程默认设计有自动建库功能，但是Oracle、MySql、MSSQL等建库需要管理员权限，XCode在权限切换时不一定成功。
你可以尝试一下其它版本XCode是否成功，如果有某个版本成功而1212不行，则说明1212有bug需要修正；如果多个版本都不行，说明环境不足以支持自动建库。

实际工作中也可以发现，自动建库功能用得非常少，毕竟谁也不会没事就drop掉一个库。

BTW，准备发布0101新年版

**Comment by armku** [comment]
程序以管理员权限运行，正常。

**Comment by nnhy** [comment]
那就是环境问题，前面说了，建库需要非常高的权限
