### ISSUE TITLE
TCP在多个TCP并发的时候  ReceivedEventArgs 有部分数据接收 不会触发，log记录是有的

### ISSUE THREAD

**Issue by lilililililililiyi** [NewLifeX/X#46]
TCP在多个TCP并发的时候  ReceivedEventArgs 有部分数据接收 不会触发，log记录是有的
目前用的是5个   网络助手 和日志  显示的都是对的    通讯没有开异步  会不会是多线程没有触发

**Comment by nnhy** [comment]
有可能是因为粘包处理所致，达不到一个包，即使底层收到，也不会触发上层事件

**Comment by lilililililililiyi** [comment]
5个连接 发送的都是相同的数据

**Comment by nnhy** [comment]
用码神监听试试，如果码神没问题，那么就是tcp使用代码有问题
网络服务器使用NetServer，不要直接使用TcpServer

**Comment by lilililililililiyi** [comment]
用wireshark监听的 没有问题 用的 就是netserver

**Comment by nnhy** [comment]
挂载源码调试分析看看，网络是比较复杂

**Comment by nnhy** [comment]
启用LogReceive后，如果日志能看到接收数据的hex，而上层代码没有触发事件，基本上是因为粘包处理有问题

**Comment by nnhy** [comment]
2月和3月有优化粘包处理部分代码，可以更新试试能否解决问题

**Comment by nnhy** [comment]
已确认NET40/NET45在粘包处理时有bug，导致该问题，已修正！
建议升级到最新NET版本
