### ISSUE TITLE
如何在ApiServer中指定某个请求为普通的post get 请求, 而不是长连接方式?

### ISSUE THREAD

**Issue by jmy10241024** [NewLifeX/X#47]
如图
![image](https://user-images.githubusercontent.com/26403812/72426915-9cfaf980-37c5-11ea-982d-774a4492dec5.png)

**Comment by nnhy** [comment]
这个需求，建议直接使用 netcore 的WebApi，效果更好。
ApiServer支持http只是为了辅助测试和跨系统对接，主力还在tcp/udp
