### ISSUE TITLE
配置文件的Bug

### ISSUE THREAD

**Issue by corsip** [NewLifeX/X#49]
版本：8.6.2020.204

配置文件使用：
```cs
[XmlConfigFile("Config/Settings.config", 15000)]
    public class Settings : Config<Settings>
    {
        public List<SsoClients> Clients { get; set; } = new List<SsoClients>() {
            new SsoClients(){
                AllowedScopes = new List<string>(){ "api1" },
                PostLogoutRedirectUris = new List<string>(){ "http://localhost:5000/" },
                RedirectUris = new List<string>(){ "http://sso.demo:5100/signin-oidc" }
            }
        };
        public List<IUsers> Users { get; set; } = new List<IUsers>() {
            new IUsers(){
                Id = "1",
                Email = "@q.com",
                Name = "muxuan",
                NickName = "muxuan",
                Password = "muxuan",
                Phone = "15711111111",
                Role = "Admin"
            }
        };
        public List<Apis> Apis { get; set; } = new List<Apis>() {
            new Apis(){ ApiName = "api1", ApiDisplayName = "接口1" }
        };
    }
```

报错信息：

![image](https://user-images.githubusercontent.com/55883022/74103376-93776e00-4b86-11ea-9c4b-04ce4803064d.png)

**Comment by nnhy** [comment]
写成单元测试，提交PR进来，我找不到合适的单元测试用例

**Comment by e4ky** [comment]
支持String[] 有问题
```
    [DisplayName("看门狗配置")]
    [Config("Watch")]
    class Settings : Config<Settings>
    {
        /// <summary>看护的程序完整路径及名称</summary>
        [Description("看护的程序完整路径及名称")]
        public String WatchProgramFullName { get; set; } = "";


        /// <summary>第二组开始的程序启动间隔时间（毫秒）</summary>
        [Description("第二组开始的程序启动间隔时间（毫秒）")]
        public int StartSecondProgramWaitTime { get; set; } = 1000;


        /// <summary>看护的程序名称(不包含后缀)</summary>
        [Description("第二组看护的程序名称列表(不包含后缀)")]
        public String[] SecondWatchProgramFullNames { get; set; } = { "" };
    }
```

报错信息

> 21:13:58.253  4 Y - System.Exception: 创建对象失败 type=System.String parameters= 没有为该对象定义无参数的构造函数。 ---> System.MissingMethodException: 没有为该对象定义无参数的构造函数。
   在 System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   在 System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   在 System.Activator.CreateInstance(Type type, Boolean nonPublic)
   在 NewLife.Reflection.DefaultReflect.CreateInstance(Type type, Object[] parameters) 位置 D:\X\Src\NewLife.Core\Reflection\IReflect.cs:行号 412
   --- 内部异常堆栈跟踪的结尾 ---
   在 NewLife.Reflection.DefaultReflect.CreateInstance(Type type, Object[] parameters) 位置 D:\X\Src\NewLife.Core\Reflection\IReflect.cs:行号 419
   在 NewLife.Configuration.ConfigProvider.MapArray(IConfigSection section, Object model, PropertyInfo pi) 位置 D:\X\Src\NewLife.Core\Configuration\IConfigProvider.cs:行号 272
   在 NewLife.Configuration.ConfigProvider.MapTo(IConfigSection section, Object model) 位置 D:\X\Src\NewLife.Core\Configuration\IConfigProvider.cs:行号 233
   在 NewLife.Configuration.FileConfigProvider.Watch_Changed(Object sender, FileSystemEventArgs e) 位置 D:\X\Src\NewLife.Core\Configuration\FileConfigProvider.cs:行号 181

**Comment by nnhy** [comment]
问题已修正，单元测试通过

Json/Xml配置文件支持字符串数组，单元测试覆盖通过
https://github.com/NewLifeX/X/commit/32e0342dea4e3a3f2fff99fc3a7976126dc9a330
