### ISSUE TITLE
多表（各个表均多数据）连接查询结果使用XCode模型问题

### ISSUE THREAD

**Issue by m446883859** [NewLifeX/X#50]
问题场景：XCode多表连接查询，针对一张主表，多业务数据，其他关联表的数据多为轻量数据表，这种情况，完全可使用扩展属性处理业务关系。查询时条件构筑可先查询ID集合再接着查询。这个没问题。如果两张表数据量都很大，这种显然不太适用。
问题目的描述：例如：两张表，各表的数据量都很多，之间又存在业务关系，对这两张表进行查询时又希望借助XCode的便利性。当然可以示用视图。但是由于很多项目为防治视图滥用禁止建立视图，所以就很难受。就有了下面的使用方式。
  [Serializable]
    [DataObject]
    [BindTable(@"(SELECT wr.*,
                       wrm.[material]
                      ,wrm.[specification]
                      ,wrm.[unit]
                      ,wrm.[suppliername]
                    FROM weighing wr INNER JOIN material wrm ON wr.id = wrm.weighing_id WHERE wr.isdeleted != 1)", 
                Description = "",
                ConnName = "Conn", 
                DbType = DatabaseType.SqlServer, 
                IsView = true)]
但是上面这种方式在注解中加入了sql，看起来也能使用。但是有点怪。  

适用方案：1.保持上面这种方式完全可以使用2. with as 的支持（群里提出的）但是并不是所有数据库都支持这个关键字3.将这个sql源设计到其他地方去不要放在注解中，注解中只添加引用。 其他更优方式有待考虑

**Comment by nnhy** [comment]
最好使用替换符来作为表名，然后在构造sql时读取真正的sql。
目前在考虑，真正的sql是写在代码里？还是独立文件？或者嵌入sql文件？

**Comment by m446883859** [comment]
我感觉目前这种情况，还是放在 独立文件中，毕竟如果别人用视图 还是用视图名字。

**Comment by nnhy** [comment]
已完成！

把视图Sql作为表名，使用实体类查询 · NewLifeX/X@fedaff3
https://github.com/NewLifeX/X/commit/fedaff3042fb4d8bcc889eae4ddf96836dfafb13
