### ISSUE TITLE
在ScanController注册系统菜单时抛出异常

### ISSUE THREAD

**Issue by Xusp** [NewLifeX/X#52]
System.Reflection.ReflectionTypeLoadException: 无法加载一个或多个请求的类型。有关更多信息，请检索 LoaderExceptions 属性。
   在 System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   在 System.Reflection.RuntimeModule.GetTypes()
   在 System.Reflection.Assembly.GetTypes()
   在 XCode.Membership.Menu`1.MenuFactory.ScanController(String rootName, Assembly asm, String nameSpace) 位置 D:\X\Src\XCode\Membership\菜单.Biz.cs:行号 389
   在 NewLife.Cube.AreaRegistrationBase.ScanController() 位置 F:\Workdir\dotNET\XIoT.Cube.Metro\NewLife.Cube\Common\AreaRegistrationBase.cs:行号 332
   在 NewLife.Threading.ThreadPoolX.<>c__DisplayClass2_0.<QueueUserWorkItem>b__0(Object s) 位置 D:\X\Src\NewLife.Core\Threading\ThreadPoolX.cs:行号 36

**Comment by Xusp** [comment]
System.Reflection.ReflectionTypeLoadException: 无法加载一个或多个请求的类型。有关更多信息，请检索 LoaderExceptions 属性。
   在 System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   在 System.Reflection.RuntimeModule.GetTypes()
   在 System.Reflection.Assembly.GetTypes()
   在 NewLife.Cube.Precompiled.PrecompiledMvcEngine.GetTypeMappings(Assembly asm, String baseVirtualPath) 位置 F:\Workdir\dotNET\XIoT.Cube.Metro\NewLife.Cube\Precompiled\PrecompiledMvcEngine.cs:行号 230

**Comment by nnhy** [comment]
新版 NewLife.Core 已经屏蔽 asm.GetTypes 异常
