### ISSUE TITLE
我想实现删除比如一年前的数据 用xcode怎样实现比较好？

### ISSUE THREAD

**Issue by 4058665** [NewLifeX/X#54]
如题

**Comment by nnhy** [comment]
var list=User.FindAll(_.CreateTime<DateTime.Now.AddYears(-1));
list.Delete();

或者 
User.Delete(_.CreateTime<DateTime.Now.AddYears(-1));

你试试，注意看它生成的sql语句

**Comment by 4058665** [comment]
非常感谢！  我用这种方式是可以删除某段时间前的所有记录了！ 日志也显示我所盼望的sql语句
但还有个场景：   我需要清空sqlite某个表的，但是清空后sqlite的数据库文件体积没减小
sqlite 语句记得是用 VACUUM来缩小尺寸 ，如果放在xcode中  可以用什么方式呢？

补上我执行的语句：
删除一年前记录
 SysLog.Delete(SysLog._.Time < DateTime.Now.AddYears(-1));

删除所有记录 ，不知道有没有更好的方法
SysLog.Delete(SysLog._.ID);

**Comment by nnhy** [comment]
清空数据
SysLog.Meta.Truncate()
