### ISSUE TITLE
建议增加功能：连接复原，类似EF Core中的 EnableRetryOnFailure

### ISSUE THREAD

**Issue by christan-duplicate** [NewLifeX/X#57]
建议增加功能：连接复原，类似EF Core中的 EnableRetryOnFailure

**Comment by nnhy** [comment]
这是一个很棒的建议，实际工作中的确经常遇到需要重试的情况。
今天晚上将会在DAL层加入该功能，dev代码分支！

**Comment by nnhy** [comment]
失败重试。执行命令超时后的重试次数，默认0不重试
https://github.com/NewLifeX/X/commit/9dc31079707c67888ea40c6488a1e4c5845db003
