### ISSUE TITLE
关于blob字段的问题

### ISSUE THREAD

**Issue by haocg2003** [NewLifeX/X#58]
由于blob字段大小不定，在批量操作时经常会出现数据量过大导致出错。能不能在生成xml时，在字段里加入一个说明，表示是否生成，或者生成时自动生成其为扩展属性。

**Comment by nnhy** [comment]
平时blob用得少，能否提供一个测试用例？

**Comment by nnhy** [comment]
blob字段应该会被识别为byte[]

**Comment by nnhy** [comment]
如果生成实体类时不想要这个字段，在XML模型文件里面删除这个字段即可
