### ISSUE TITLE
建议：将NewLife.Core/Extension下扩展方法的命名空间（namespace System）迁移到其他的命名空间，以避免和其他团队的扩展方法冲突。

### ISSUE THREAD

**Issue by thxu** [NewLifeX/X#59]
最近我们团队打算使用NewLife.RocketMQ组件，这个组件又引用了NewLife.Core组件。
现在我们引用了NewLife.RocketMQ组件后项目大量报引用冲突错误。

原因：
我们团队对字符串、列表等常用操作封装了自己的扩展方法，如`IsNullOrEmpty()`，
而NewLife.Core组件中对字符串、列表等操作也封装了扩展方法，且命名空间在System下面，
这就导致了如果我们使用System命名空间，则必然引入了NewLife.Core组件的扩展方法，此时如果我们再引入我们自己的扩展方法，就会报错，提示`以下方法或属性之间的调用具有二义性`

我们既不可能放弃使用System命名空间，也不可能放弃我们自己的扩展方法（因为里面还有一些业务相关的代码），这给我们使用NewLife相关组件造成了极大的困扰。

希望NewLife团队采纳此建议。

**Comment by nnhy** [comment]
这个问题的确存在，也争论了好些年。主要问题在于，newlife.core的扩展方法，始于很多很多年前，我们已经有了太多的应用使用，如果贸然修改命名空间，会带来一定困扰。

这个我们再讨论，如果可行，可能会把这些扩展的命名空间改为 NewLife 或者 NewLife.Extensions

**Comment by nnhy** [comment]
!!!字符串扩展StringHelper命名空间由System改为NewLife，避免跟第三方组件冲突 · NewLifeX/X@228add0
https://github.com/NewLifeX/X/commit/228add07ef7e398abdf914169de5dac7b77eda7a
