### ISSUE TITLE
基于Sqlite数据库使用 EntityBuilder.BuildTables 生成实体代码报错

### ISSUE THREAD

**Issue by shuta85** [NewLifeX/X#60]
由于xcode的netcore不再提供动态编译功能，所以我需要使用EntityBuilder.BuildTables 生成实体代码后再动态编译。

发现基于Sqlite数据库的动态编译会报错，问题在于其他数据库使用DbMetaData获取IDataTable信息，里面会设置IDataColumn的Name属性，但是Sqlite使用SQLiteMetaData类初始化信息，却没有设置Name这个属性。

于是在EntityBuilder的某处地方有个Name.ToLower()的代码，并没有判断Name是否null导致报错。所以EntityBuilder.BuildTables目前对于Sqlite是没有作用的。

建议的处理方式就是在SQLiteMetaData里也给IDataColumn额外的设置值，如果没有值则取ColumnName

**Comment by nnhy** [comment]
修改一下，提交PR

**Comment by nnhy** [comment]
这个问题应该已经处理过了，你再试试
