### ISSUE TITLE
日志组件是否可以加个配置，不同日志类型不同存储目录，方便管理查看不同日志

### ISSUE THREAD

**Issue by dingzl2004** [NewLifeX/X#61]
日志组件是否可以加个配置，不同日志类型不同存储目录，方便管理查看不同日志

**Comment by nnhy** [comment]
已完成！

https://github.com/NewLifeX/X/commit/85c6ebad9304d213426f4623d6b764aa6a834fc1

**Comment by nnhy** [comment]
已完成！

https://github.com/NewLifeX/X/commit/85c6ebad9304d213426f4623d6b764aa6a834fc1
