### ISSUE TITLE
如果 UseParameter 为 false 的话，查询 GUID 会报错

### ISSUE THREAD

**Issue by christan-duplicate** [NewLifeX/X#62]
如果 UseParameter 为 false 的话，查询 GUID 会报错
![image](https://user-images.githubusercontent.com/769138/90121537-aa458a00-dd8e-11ea-9416-cf2e2c6b7920.png)

输出的sql没有用 引号括起来

**Comment by christan-duplicate** [comment]
如果 UseParameter 为 true，开启参数查询后，如果某个值为空或null，则会生成以下sql，导致报错：@Ip=, 这个=号后面什么都没有。
`
Update Code Set Ip=@Ip,Used=@Used Where CodeId=@CodeId [@Ip=, @Used=True, @CodeId=1949]
`

**Comment by nnhy** [comment]
难道是因为guid查询没有加双引号？

**Comment by nnhy** [comment]
![image](https://user-images.githubusercontent.com/506367/93404792-b6f15c80-f8bd-11ea-9543-4c77426b34a3.png)

检查了代码，guid数据会加双引号

**Comment by christan-duplicate** [comment]
字段是必填的，但没有初始化这个字段，所以报null错误了。

**Comment by nnhy** [comment]
模型文件里面，这个字段设置 nullable=false，再试试
