### ISSUE TITLE
.net5 SqlServer _Factory = GetProviderFactory(null, "System.Data.SqlClient.SqlClientFactory") null

### ISSUE THREAD

**Issue by christan-duplicate** [NewLifeX/X#66]
14:17:25.496  7 Y - System.Data.SqlClient.Sql驱动D:\Web\bin\Debug\net5.0\Plugins\System.Data.SqlClient.dll 版本v4.6.1.2

![QQ图片20201119143222](https://user-images.githubusercontent.com/769138/99630059-24fc0080-2a74-11eb-9a51-f5995110e825.png)

return Reflect.GetValue(null, field) as DbProviderFactory;
这一步后，返回null。

![QQ图片20201119143923](https://user-images.githubusercontent.com/769138/99630566-1530ec00-2a75-11eb-854e-356b2c684936.png)

**Comment by nnhy** [comment]
.net5.0对于各个数据库的兼容，还需要加强测试
