### ISSUE TITLE
希望这个修改索引名的功能做个开关，让不需要的可以禁止修改，谢谢

### ISSUE THREAD

**Issue by christan-duplicate** [NewLifeX/X#70]
X\XCode\Entity\EntitySession.cs

![image](https://user-images.githubusercontent.com/769138/105002803-ce5b7480-5a6c-11eb-85b8-51afaf830b85.png)

**Comment by nnhy** [comment]
已支持！

实体类索引已有名称时，不再生成修正版索引名 · NewLifeX/X@efc0758
https://github.com/NewLifeX/X/commit/efc075829d933e56b5884320344c4f2dab9ecdbb
