### ISSUE TITLE
Visual Studio-16.9.1 Net5.0.4 Build_netcore.tt 运行自定义工具异常

### ISSUE THREAD

**Issue by ClueeZhuo** [NewLifeX/X#73]
大石头，nfx4.6.1项目安装NewLife.XCode后生成Entity文件夹，然后我把Build_netcore.tt和Model.xml拷贝到NET 5控制台目录下，然后右键运行自定义工具。
Visual Studio-16.9.1
提示如下错误：
严重性	代码	说明	项目	文件	行	禁止显示状态
错误  正在编译转换: 类型“IList<>”在未引用的程序集中定义。必须添加对程序集“System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”的引用。	Tech.Cluee.Blazor.XCode	D:\GIT\Tech.Cluee.Blazor\Main\Tech.Cluee.Blazor.XCode\Build_netcore.tt	19  
错误  正在编译转换: 类型“Object”在未引用的程序集中定义。必须添加对程序集“System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”的引用。	Tech.Cluee.Blazor.XCode	D:\GIT\Tech.Cluee.Blazor\Main\Tech.Cluee.Blazor.XCode\Build_netcore.tt	19  
错误  正在编译转换: 类型“IDictionary<,>”在未引用的程序集中定义。必须添加对程序集“System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”的引用。	Tech.Cluee.Blazor.XCode	D:\GIT\Tech.Cluee.Blazor\Main\Tech.Cluee.Blazor.XCode\Build_netcore.tt	20

**Comment by qcjxberin** [comment]
我也遇到过，我目前是专门建一个类来生成到指定项目的文件夹中

**Comment by nnhy** [comment]
可以参考零代脚手架 NewLife.Zero
我们都是在解决方案目录下，新建一个DLL子目录，把netcore31的newlife.core.dll和xcode.dll放进去，然后build.tt直接引用。
类似这样：

<#@ template language="C#" hostSpecific="true" debug="true" #>
<#@ assembly name="netstandard" #>
<#@ assembly name="$(SolutionDir)\DLL\NewLife.Core.dll" #>
<#@ assembly name="$(SolutionDir)\DLL\XCode.dll" #>
<#@ import namespace="System.Diagnostics" #>
<#@ import namespace="System.IO" #>
<#@ import namespace="XCode.Code" #>
<#@ output extension=".log" #>

**Comment by ClueeZhuo** [comment]
嗯嗯，问题解决了，主要是路径问题。下面种方式正常使用，
<#@ assembly name="$(SolutionDir)\DLL\NewLife.Core.dll" #>
<#@ assembly name="$(SolutionDir)\DLL\XCode.dll" #>

如下方式测试证明不能够正常
<#@ assembly name="$(ProjectDir)\$(OutputPath)\NewLife.Core.dll" #>
<#@ assembly name="$(ProjectDir)\$(OutputPath)\XCode.dll" #>
