### ISSUE TITLE
vs 2015 打开加载报错

### ISSUE THREAD

**Issue by JacobLiou** [NewLifeX/X#76]
直接下载zip 解压 打开sln 出现报错

**Comment by nnhy** [comment]
必须安装vs2019并打到最新补丁

**Comment by qurikuduo** [comment]
2015要升级了。

**Comment by nnhy** [comment]
项目用了最新C#语法，所以需要新的编译器才行。
尽管这样，编译目标还是包括 .net4.0/.net5.0 等等
