### ISSUE TITLE
请问能同时支持多数据库吗

### ISSUE THREAD

**Issue by 4058665** [NewLifeX/X#80]
比如同时支持mysql 和sqlite

**Comment by qcjxberin** [comment]
可以的

**Comment by 4058665** [comment]
有简单的例子吗  ？   我这边有个需求 一般的配置放到sqlite中   连续的非重点记录放到mysql中     
低性能的机子发现有记录损坏的情况 而导致整个系统不能工作了

**Comment by 4058665** [comment]
> 可以的

谢谢大佬  有相关使用的文档说明或者例子吗 我这边有个需求 一般的配置放到sqlite中 连续的非重点记录放到mysql中
低性能的机子发现有记录损坏的情况 而导致整个系统不能工作了

**Comment by qcjxberin** [comment]
默认如果不做配置的话就是sqite数据库。

**Comment by qcjxberin** [comment]
![image](https://user-images.githubusercontent.com/5792218/119259643-c457a700-bc01-11eb-953f-dfed4e976767.png)
![image](https://user-images.githubusercontent.com/5792218/119259653-cde10f00-bc01-11eb-8aea-6b04f413d765.png)
也可以针对单设置ConnName

**Comment by qcjxberin** [comment]
也可以针对单表设置ConnName
