### ISSUE TITLE
智能大石头，我想请教下 IPlugin 这个插件如何使用？

### ISSUE THREAD

**Issue by ClueeZhuo** [NewLifeX/X#81]
智能大石头，我想请教下 IPlugin 这个插件如何使用？提供下文档否？

**Comment by nnhy** [comment]
IPlugin是早期产品，试图统一在各个产品中的插件接口实现。
后来发现这个方向不可行，在不同的业务方向，插件实现还是有所不同。

**Comment by ClueeZhuo** [comment]
好的，大石头。目前你这边是否有插件开发接口实现方案？

**Comment by nnhy** [comment]
IPipeline 就是比较高级的链式插件实现，普通插件可以参考序列化目录，各种IHandler
