### ISSUE TITLE
DefaultMatchQueue的超时值不做最大限制

### ISSUE THREAD

**Issue by wweifu** [NewLifeX/X#82]
[代码](https://github.com/NewLifeX/X/blob/53f67916ce587817677c68098c79397f43f3b875/NewLife.Core/Net/Handlers/IMatchQueue.cs#L48) 有时候需要一个很大的超时值,想修改修改不了 希望新版能改下,辛苦了!~~

**Comment by nnhy** [comment]
已解决！ https://github.com/NewLifeX/X/commit/a4d8c4462e6831d2a820ed6231c33771a6b5ab7e
