### ISSUE TITLE
RPC通信在Packet大小超过8KB的时候也会出错，这个有长度限制吗？

### ISSUE THREAD

**Issue by zhangzhui** [NewLifeX/X#85]
vs:2019
.net framework: 4.0
newlife.core: 8.11.2021.809

用PostMan试了一下，超过8KB，server端能够接收正常，这个看来是ApiClient的问题，需要有什么配置吗？
用wireshark抓数据帧，ApiClient将数据正确发送给了server，server端也接收到了，但是就是没有响应。

这个跟这个[bug](https://github.com/NewLifeX/X/issues/84)应该是同一个问题
用Postman没有问题是因为我自己重新了一个http session

**Comment by nnhy** [comment]
RPC数据包有帧头，对方需要等到帧头指定的全部数据，才会触发接口调用。

**Comment by zhangzhui** [comment]
用wireshark截取数据帧，可以看到所有的数据都发过去了。因为我是在本地测试，所以不可能会有拆包的情况，而且ApiServer也回复了ack，所以ApiServer也肯定是收到了数据。但是超过了8KB（默认大小），所以在解析数据包的时候就会有问题。也就是下图没有进行深拷贝。见[bug](https://github.com/NewLifeX/X/issues/84)里的描述

请看下wireshark截图（里面传输了一个24KB的文件），问题已经指向了ApiServer
![image](https://user-images.githubusercontent.com/7258591/130542332-6cc1f82e-45fb-4103-bdf2-3e3d824c672e.png)

**Comment by nnhy** [comment]
我明白，ApiServer所使用的编码器具有粘包处理功能，理论上不会出问题。待会我增加一个RPC的大消息单元测试，看看问题在哪。

**Comment by nnhy** [comment]
![image](https://user-images.githubusercontent.com/506367/130555116-868a0f0b-c290-4ded-b4b0-7b92e4b10fc1.png)
加了个RPC的大消息单元测试，测试通过，能够正确传输大消息。
你看看测试用例是否满足你的场景，也可以提交PR把你的测试用例加进来

**Comment by zhangzhui** [comment]
您把地址修改为tcp://127.0.0.1:12399试一试。
您这个单例应该是建立在修改了HttpResponse的clone之上的，所以http协议没有问题
但是tcp协议还是不行

**Comment by nnhy** [comment]
刚试过了，换成tcp也没有问题，你试试看

**Comment by zhangzhui** [comment]
[WpfApp2.zip](https://github.com/NewLifeX/X/files/7036533/WpfApp2.zip)
新建立了一个工程，您看看有什么写的不对的地方吗？

**Comment by nnhy** [comment]
晚上回去试一下，今天一整天开会

**Comment by nnhy** [comment]
已确认某个基础类库在.NET4.0/.NET4.5上有bug，导致RPC封包的粘包处理失效。
该问题在.NET4.6及以上不存在，我们的单元测试用例全部都是.NET5.0。
今晚修复这个bug

**Comment by nnhy** [comment]
你这边测试通过了吗？
把你的项目改为4.6或以上，没有问题。
或者拉取最新代码编译，也可以解决问题。

**Comment by zhangzhui** [comment]
我拉取最新代码测试过了
