### ISSUE TITLE
关于配置文件

### ISSUE THREAD

**Issue by chao137** [NewLifeX/X#89]
请问如何更改默认的配置Setting？

**Comment by nnhy** [comment]
一般在应用启动文件里面，例如startup，这样写
if(set.IsNew){
set.xxx = yyy;
set.save();
}

**Comment by chao137** [comment]
是这样的，我这边使用的是.net6的woker service，当我没有做任何配置时，使用XTrace会生成默认的配置文件，但我不知道怎么更改这个默认的配置

**Comment by chao137** [comment]
IHost host = Host.CreateDefaultBuilder(args)
    .ConfigureAppConfiguration(configure =>
    {
        configure.AddJsonFile("appsettings.Development.json");
    })
    .ConfigureServices(services =>
    {
        services.AddHostedService<CommunicationWorker>();
        services.AddHostedService<MqProducerService>();
        services.AddHostedService<MqConsumerService>();
    })
    .Build();
await host.RunAsync();

**Comment by chao137** [comment]
// MqProducerService.cs
        private void Producer()
        {
            XTrace.UseConsole(true, false);
            var mq = new Producer
            {
                Topic = "nx_test",
                NameServerAddress = "127.0.0.1:9876",
                Log = XTrace.Log,
            };

            mq.Start();

            mq.CreateTopic("nx_test", 2);
            for (var i = 0; i < 10; i++)
            {
                var str = "学无先后达者为师" + i;
                //var str = Rand.NextString(1337);

                NewLife.RocketMQ.Protocol.SendResult sendResult = mq.Publish(str, "TagA", $"key{i}");
            }
            mq.Dispose();
        }

**Comment by nnhy** [comment]
配置文件就放在config目录下

**Comment by chao137** [comment]
好的，感谢您的回答！目前我仍有个疑问，当我没有做任何配置时首次运行程序会帮我生成这样的目录结构：
--Config
  ├-Core.config
  └-xxx.config
--Log
  └-yyyy_MM_dd.log
--Data
  └-machinexxx.json
目前我能了解到的是，要生成后我才能去更改这些配置的结构(Config目录暂不知是否能改)，请问是否有方法能够在我首次运行程序时就按照我自己制定的配置去生成这些配置文件呢？期待您的回复！

**Comment by nnhy** [comment]
开发环境运行，生成一次，然后把 Config目录以及你需要的config文件放到项目里面，做成编译时较新复制，输出目录就有了。然后发布的时候带着config目录一起发布

**Comment by chao137** [comment]
好的，感谢
