### ISSUE TITLE
关于TcpSession关闭的问题

### ISSUE THREAD

**Issue by 541728305** [NewLifeX/X#90]
@nnlny 您好！
TcpSession实现的客户端在调用 的Close()方法时，发现服务端无法识别出来断开信号；用Sockets.TcpClient 实现的客户端调用Close()方法时服务端就可以识别断开信号，请问这是为什么呢？目标框架是.Net 4.0，期待您的回复。

`TcpSession tcpSession = new TcpSession();
        System.Net.Sockets.TcpClient TcpClient = new System.Net.Sockets.TcpClient();
        bool IsConnect = false;
        private void ConnectButton_Click(object sender, EventArgs e)
        {
            if (!IsConnect)
            {
                tcpSession.Opened += TcpSession_Opened;
                tcpSession.Remote = this.RemoteAddrTextBox.Text + ":" + this.RemotePortTextBox.Text;
         
                try
                {
                    tcpSession.Open();
                    //TcpClient.Connect(this.RemoteAddrTextBox.Text,Convert.ToInt32(this.RemotePortTextBox.Text));                 
                    //this.ConnectButton.Text = "断开";
                    //IsConnect = true;

                }
                catch (Exception ex)
                {
                    MessageBox.Show(ex.Message);
                }
            }
            else
            {
                tcpSession.Close("User Close");
                //TcpClient.Close();
                //IsConnect = false;
                //this.ConnectButton.Text = "连接";
            }
        }`

**Comment by 541728305** [comment]
tcpSession.Close() 没有包含socket shutdown吗，手动调用shutdown就可以了

**Comment by nnhy** [comment]
`protected override Boolean OnClose(String reason)
{
    var client = Client;
    if (client != null)
    {
        WriteLog("Close {0} {1}", reason, this);

        // 提前关闭这个标识，否则Close时可能触发自动重连机制
        Active = false;
        try
        {
            // 温和一点关闭连接
            //Client.Shutdown();
            client.Close();

            // 如果是服务端，这个时候就是销毁
            if (_Server != null) Dispose();
        }
        catch (Exception ex)
        {
            Client = null;
            if (!ex.IsDisposed()) OnError("Close", ex);
            //if (ThrowException) throw;

            return false;
        }
        Client = null;
    }

    return true;
}
`
如上，2015年5月1日的时候，把shutdown注释了，当时的注释写得不是很清楚。
现在已经加回去

**Comment by 541728305** [comment]
好的，谢谢

**Comment by 541728305** [comment]
> `protected override Boolean OnClose(String reason) { var client = Client; if (client != null) { WriteLog("Close {0} {1}", reason, this);
> 
> ```
>     // 提前关闭这个标识，否则Close时可能触发自动重连机制
>     Active = false;
>     try
>     {
>         // 温和一点关闭连接
>         //Client.Shutdown();
>         client.Close();
> 
>         // 如果是服务端，这个时候就是销毁
>         if (_Server != null) Dispose();
>     }
>     catch (Exception ex)
>     {
>         Client = null;
>         if (!ex.IsDisposed()) OnError("Close", ex);
>         //if (ThrowException) throw;
> 
>         return false;
>     }
>     Client = null;
> }
> 
> return true;
> ```
> 
> } ` 如上，2015年5月1日的时候，把shutdown注释了，当时的注释写得不是很清楚。 现在已经加回去



> `protected override Boolean OnClose(String reason) { var client = Client; if (client != null) { WriteLog("Close {0} {1}", reason, this);
> 
> ```
>     // 提前关闭这个标识，否则Close时可能触发自动重连机制
>     Active = false;
>     try
>     {
>         // 温和一点关闭连接
>         //Client.Shutdown();
>         client.Close();
> 
>         // 如果是服务端，这个时候就是销毁
>         if (_Server != null) Dispose();
>     }
>     catch (Exception ex)
>     {
>         Client = null;
>         if (!ex.IsDisposed()) OnError("Close", ex);
>         //if (ThrowException) throw;
> 
>         return false;
>     }
>     Client = null;
> }
> 
> return true;
> ```
> 
> } ` 如上，2015年5月1日的时候，把shutdown注释了，当时的注释写得不是很清楚。 现在已经加回去

好的，谢谢

**Comment by nnhy** [comment]
元旦发布了1月份正式版  2022.0101
