### ISSUE TITLE
在 Xamarin.Forms项目中无法使用 XCode（sqlite数据库）

### ISSUE THREAD

**Issue by prosourcegithub** [NewLifeX/X#96]
在 Xamarin.Forms项目中使用 XCode，会自动尝试到 http://x.newlifex.com/ 上下载 sqlite 驱动“ Mono.Data.Sqlite.dll”，但网页中并没有这个sqlite驱动。手动在Android项目中添加引用  Mono.Data.Sqlite.dll ，也会发生无法正常加载驱动的异常。

**Comment by nnhy** [comment]
在nuget中查找适用于xamarin的sqlite驱动，直接安装。如果xcode未能识别，则需要修改XCode中的SQLite.cs，增加判断支持。

**Comment by prosourcegithub** [comment]
希望能在 https://x.newlifex.com/ 网站添加xamarin目前最新版本能用的sqlite驱动。

**Comment by nnhy** [comment]
帮忙从nuget中找一个可用版本，然后我来添加到驱动站

**Comment by prosourcegithub** [comment]
这个问题我摸索了一天。在nuget上试装了和Sqlite有关的几个库，都不能让XCode正常用在Xamarin上。				
从VS2022文件夹“C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\bcl” 中找到的 Mono.Data.Sqlite.dll 里面没有“Mono.Data.Sqlite.SqliteFactory” 这个类，因此不能直接使用。				
				
目前不优雅但能正常工作的解决方案：				
	1、自己继承DbProviderFactory实现一个工厂类，如：			
		using System.Data.Common;		
		using Mono.Data.Sqlite;		
		namespace System.Data		
		{		
		    public class SqliteFactory : DbProviderFactory		
		    {	……	}
		}		
				
	该类可以写在XCode或者Xamarin共享项目。需要在项目中手动添加对 Mono.Data.Sqlite.dll 的引用。			
				
	2、修改 XCode\DataAccessLayer\Database\SQLite.cs：			
		原：_Factory = GetProviderFactory("Mono.Data.Sqlite.dll", "Mono.Data.Sqlite.SqliteFactory");		
		修改为：_Factory = GetProviderFactory("Mono.Data.Sqlite.dll", "System.Data.SqliteFactory");		
				
	3、在Android项目中手动添加对 Mono.Data.Sqlite.dll 的引用。			
		Android API 23 之后不允许访问 /lib/libsqlite.so，添加该dll后apk自动打包使用 libsqlite3_xamarin.so。

**Comment by nnhy** [comment]
已提交修改！workflow会发布一个beta版到nuget
